name: abherbs_flutter
description: Flutter version of abherbs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 5.0.0+500

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  firebase_database: 1.0.5
  firebase_admob: 0.7.0
  url_launcher: 4.0.3
  http: 0.12.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/images/home.png
    - res/images/placeholder.webp
    - res/images/white.webp
    - res/images/yellow.webp
    - res/images/red.webp
    - res/images/blue.webp
    - res/images/green.webp
    - res/images/forest.webp
    - res/images/garden.webp
    - res/images/meadow.webp
    - res/images/mountain.webp
    - res/images/swamp.webp
    - res/images/tree.webp
    - res/images/nop_4.webp
    - res/images/nop_5.webp
    - res/images/nop_many.webp
    - res/images/nop_zygomorphic.webp
    - res/images/wgsrpd_africa.webp
    - res/images/wgsrpd_antarctic.webp
    - res/images/wgsrpd_arabian_peninsula.webp
    - res/images/wgsrpd_asia_temperate.webp
    - res/images/wgsrpd_asia_tropical.webp
    - res/images/wgsrpd_australasia.webp
    - res/images/wgsrpd_australia.webp
    - res/images/wgsrpd_brazil.webp
    - res/images/wgsrpd_caribbean.webp
    - res/images/wgsrpd_caucasus.webp
    - res/images/wgsrpd_central_america.webp
    - res/images/wgsrpd_central_tropical_africa.webp
    - res/images/wgsrpd_east_asia.webp
    - res/images/wgsrpd_east_tropical_africa.webp
    - res/images/wgsrpd_eastern_canada.webp
    - res/images/wgsrpd_eastern_europe.webp
    - res/images/wgsrpd_europe.webp
    - res/images/wgsrpd_china.webp
    - res/images/wgsrpd_indian_subcontinent.webp
    - res/images/wgsrpd_indochina.webp
    - res/images/wgsrpd_macaronesia.webp
    - res/images/wgsrpd_malesia.webp
    - res/images/wgsrpd_mexico.webp
    - res/images/wgsrpd_middle_asia.webp
    - res/images/wgsrpd_middle_atlantic_ocean.webp
    - res/images/wgsrpd_middle_europe.webp
    - res/images/wgsrpd_mongolia.webp
    - res/images/wgsrpd_my_region.webp
    - res/images/wgsrpd_new_zealand.webp
    - res/images/wgsrpd_north_central_pacific.webp
    - res/images/wgsrpd_north_central_united_states.webp
    - res/images/wgsrpd_northeast_tropical_africa.webp
    - res/images/wgsrpd_northeastern_united_states.webp
    - res/images/wgsrpd_northern_africa.webp
    - res/images/wgsrpd_northern_america.webp
    - res/images/wgsrpd_northern_europe.webp
    - res/images/wgsrpd_northern_south_america.webp
    - res/images/wgsrpd_northwestern_pacific.webp
    - res/images/wgsrpd_northwestern_united_states.webp
    - res/images/wgsrpd_pacific.webp
    - res/images/wgsrpd_papuasia.webp
    - res/images/wgsrpd_russian_far_east.webp
    - res/images/wgsrpd_siberia.webp
    - res/images/wgsrpd_south_central_pacific.webp
    - res/images/wgsrpd_south_central_united_states.webp
    - res/images/wgsrpd_south_tropical_africa.webp
    - res/images/wgsrpd_southeastern_europe.webp
    - res/images/wgsrpd_southeastern_united_states.webp
    - res/images/wgsrpd_southern_africa.webp
    - res/images/wgsrpd_southern_america.webp
    - res/images/wgsrpd_southern_south_america.webp
    - res/images/wgsrpd_southwestern_europe.webp
    - res/images/wgsrpd_southwestern_pacific.webp
    - res/images/wgsrpd_southwestern_united_states.webp
    - res/images/wgsrpd_subarctic_america.webp
    - res/images/wgsrpd_west_tropical_africa.webp
    - res/images/wgsrpd_western_asia.webp
    - res/images/wgsrpd_western_canada.webp
    - res/images/wgsrpd_western_indian_ocean.webp
    - res/images/wgsrpd_western_south_america.webp
    - res/images/color.png
    - res/images/habitat.png
    - res/images/petal.png
    - res/images/distribution.png
    - res/images/ic_flower_grey_24dp.png
    - res/images/ic_fruit_grey_24dp.png
    - res/images/ic_home_grey_24dp.png
    - res/images/ic_inflorescence_grey_24dp.png
    - res/images/ic_leaf_grey_24dp.png
    - res/images/ic_local_pharmacy_grey_24dp.png
    - res/images/ic_question_mark_grey_24dp.png
    - res/images/ic_stem_grey_24dp.png
    - res/images/ic_toxicity_grey_24dp.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
